
-- 修改表的字段名称 DESCRIBE 改为 DESCRIPTION
alter table COM_DATASOURCE rename column DESCRIBE to DESCRIPTION;
alter table COM_PROPERTIES rename column DESCRIBE to DESCRIPTION;
alter table IM_METADATA rename column DESCRIBE to DESCRIPTION;
alter table IM_MODEL rename column DESCRIBE to DESCRIPTION;
alter table IM_MODEL_FILTER_COLUMN rename column DESCRIBE to DESCRIPTION;
alter table IM_METADATA_COLUMN rename column DESCRIBE to DESCRIPTION;
alter table IM_MODEL_MAPPING rename column DESCRIBE to DESCRIPTION;
alter table IQ_APPLICATION rename column DESCRIBE to DESCRIPTION;
alter table IQ_APPLICATION_RETURN_COLUMN rename column DESCRIBE to DESCRIPTION;
alter table IQ_APPLICATION_ORDER_COLUMN rename column DESCRIBE to DESCRIPTION;
alter table IQ_APPLICATION_QUERY_COLUMN rename column DESCRIBE to DESCRIPTION;
alter table IQ_METADATA rename column DESCRIBE to DESCRIPTION;
alter table IQ_METADATA_COLUMN rename column DESCRIBE to DESCRIPTION;
alter table OLQ_APPLICATION rename column DESCRIBE to DESCRIPTION;
alter table MM_MODEL_INFO rename column DESCRIBE to DESCRIPTION;
alter table MM_APPLICATION rename column DESCRIBE to DESCRIPTION;
alter table MM_APPLICATION_RETURN_PARAM rename column DESCRIBE to DESCRIPTION;
alter table MM_APPLICATION_EXECUTE_PARAM rename column DESCRIBE to DESCRIPTION;
alter table MM_MODEL_PARAM rename column DESCRIBE to DESCRIPTION;
alter table RC_SERVICE rename column DESCRIBE to DESCRIPTION;
alter table RTS_CUSTOMER_CONFIG rename column DESCRIBE to DESCRIPTION;
alter table RTS_METADATA rename column DESCRIBE to DESCRIPTION;
alter table RTS_METADATA_COLUMN rename column DESCRIBE to DESCRIPTION;
alter table RTS_PRODUCRER_CONFIG rename column DESCRIBE to DESCRIPTION;

-- 修改表的字段名称 PRIMARY 改为 UNIQUEKEY
alter table IM_METADATA_COLUMN rename column PRIMARY to UNIQUEKEY;
alter table IM_MODEL_MAPPING rename column PRIMARY to UNIQUEKEY;

-- IM_METADATA表添加索引
create index IDX_IM_MD_DELFLG on IM_METADATA (DEL_FLG);
create index IDX_IM_MD_DELFLG_NAME on IM_METADATA (DEL_FLG, NAME);

-- IM_METADATA_COLUMN表添加索引
create index IDX_IM_MD_COL_MDID on IM_METADATA_COLUMN (MD_ID);

-- IM_MODEL表添加索引
create index IDX_IM_MODEL_DELFLG on IM_MODEL (DEL_FLG);
create index IDX_IM_MODEL_DELFLG_NAME on IM_MODEL (DEL_FLG, NAME);

-- IM_MODEL_FILTER_COLUMN表添加索引
create index IDX_IM_MODEL_FILTER_MODELID on IM_MODEL_FILTER_COLUMN (MODEL_ID);

-- IM_MODEL_MAPPING表添加索引
create index IDX_IM_MODEL_MAPPING_MODELID on IM_MODEL_MAPPING (MODEL_ID);

-- IM_MODEL_UPDATE_KEY表添加索引
create index IDX_IM_MODEL_UPDATEKEY_MODELID on IM_MODEL_UPDATE_KEY (MODEL_ID);


