-- IM_METADATA表添加索引
create index IDX_IM_MD_DELFLG on IM_METADATA (DEL_FLG);
create index IDX_IM_MD_DELFLG_NAME on IM_METADATA (DEL_FLG, NAME);

-- IM_METADATA_COLUMN表添加索引
create index IDX_IM_MD_COL_MDID on IM_METADATA_COLUMN (MD_ID);

-- IM_MODEL表添加索引
create index IDX_IM_MODEL_DELFLG on IM_MODEL (DEL_FLG);
create index IDX_IM_MODEL_DELFLG_NAME on IM_MODEL (DEL_FLG, NAME);

-- IM_MODEL_FILTER_COLUMN表添加索引
create index IDX_IM_MODEL_FILTER_MODELID on IM_MODEL_FILTER_COLUMN (MODEL_ID);

-- IM_MODEL_MAPPING表添加索引
create index IDX_IM_MODEL_MAPPING_MODELID on IM_MODEL_MAPPING (MODEL_ID);

-- IM_MODEL_UPDATE_KEY表添加索引
create index IDX_IM_MODEL_UPDATEKEY_MODELID on IM_MODEL_UPDATE_KEY (MODEL_ID);


